#pragma once
#ifndef GAME_H
#define GAME_H
#include "Global.h"
#include <list>
#include "Vector2D.h"

using std::list;

#define ITEM_NAME_SIZE 50
#define CHAR_NAME_SIZE 50
#define INVENTORY_SIZE 16


enum MOB_INTERACTION {INTERACTION_ACCESS, INTERACTION_COLLISION, INTERACTION_ATTACK,};
enum MOB_STATE { MOB_STANBY,MOB_STOP, MOB_MOVE,MOB_UGGRO, MOB_BATTLE,  };
enum EQUIPMENT_TYPE { HAT = 1, ARMOR, GLOVE, SHOSE};
enum WEAPON_TYPE {SWORD = 1, ARROW};
enum POTION_TYPE {HP_POTION, MP_POTION};

enum Chractor_Action 
{
	Jump,
	Attak,
	Skill1,
	Skill2,
	On_Damage,
};


//----Job
enum JOB_CODE
{
	JOB_WARRIOR = 101,
	JOB_ARCHER,
	JOB_MAGICIAN
};

//-----MONSTER
enum MONSTER_CODE
{
	GIANT_EYES = 201,
	GOBLIN_ARCHER,
	MINOTAUR,
	DEVIL,
};

//-----ITME
enum ITEM_CODE
{
	POTION_HP = 301,
	POTION_MP,
};

//------EQU 직업코드,0,장비번호,장비단계
enum EQUIPMENT_CODE
{
	//전사 무기
	WARRIOR_LOW_WEAPON = 1011,
	WARRIOR_MID_WEAPON,
	WARRIOR_HIGH_WEAPON,
	//전사 장비
	WARRIOR_LOW_ARMOR = 1021,
	WARRIOR_MID_ARMOR,
	WARRIOR_HIGH_ARMOR,
	WARRIOR_LOW_SHOES = 1031,
	WARRIOR_MID_SHOES,
	WARRIOR_HIGH_SHOES,
	WARRIOR_LOW_HAT = 1041,
	WARRIOR_MID_HAT,
	WARRIOR_HIGH_HAT,
	WARRIOR_LOW_GLOVE = 1051,
	WARRIOR_MID_GLOVE,
	WARRIOR_HIGH_GLOVE,

	//궁수 무기
	ARCHER_LOW_WEAPON = 2011,
	ARCHER_MID_WEAPON,
	ARCHER_HIGH_WEAPON,
	//궁수 장비
	ARCHER_LOW_ARMOR = 2021,
	ARCHER_MID_ARMOR,
	ARCHER_HIGH_ARMOR,
	ARCHER_LOW_SHOES = 2031,
	ARCHER_MID_SHOES,
	ARCHER_HIGH_SHOES,
	ARCHER_LOW_HAT = 2041,
	ARCHER_MID_HAT,
	ARCHER_HIGH_HAT,
	ARCHER_LOW_GLOVE = 2051,
	ARCHER_MID_GLOVE,
	ARCHER_HIGH_GLOVE,

	//마법사 무기
	MAGICIAN_LOW_WEAPON = 3011,
	MAGICIAN_MID_WEAPON,
	MAGICIAN_HIGH_WEAPON,
	//마법사 장비
	MAGICIAN_LOW_ARMOR = 3021,
	MAGICIAN_MID_ARMOR,
	MAGICIAN_HIGH_ARMOR,
	MAGICIAN_LOW_SHOES = 3031,
	MAGICIAN_MID_SHOES,
	MAGICIAN_HIGH_SHOES,
	MAGICIAN_LOW_HAT = 3041,
	MAGICIAN_MID_HAT,
	MAGICIAN_HIGH_HAT,
	MAGICIAN_LOW_GLOVE = 3051,
	MAGICIAN_MID_GLOVE,
	MAGICIAN_HIGH_GLOVE,
};

enum DIRECTION
{
	LEFT,
	RIGHT
};

enum CHAR_STATE
{
	IDLE,
	MOVE,
	JUMP_UP,
	JUMP_CHANGE,
	JUMP_DOWN
};

#endif // !GAME_H
